### ISSUE TITLE
Layout redesign phase 1 - rename

### ISSUE THREAD

**Issue by joshuafcole** [LightTable/LightTable#1610]
Phase 1 of #1609

## Phase 1 - Rename
* [X] Rename DOM ids
* [X] Update skin and structure
* [X] Rename statusbar symbols -> status
* [X] Rename statusbar-container symbols -> statusbar
* [X] Rename statusbar symbols / ns / file -> status-bar
* [X] Rename statusbar behaviors -> status-bar
* [X] Investigate / maybe rename sidebar symbols / ns / file -> left-bar
* [X] Investigate / maybe rename bottombar symbols / ns / file -> bottom-bar
* [X] Rename side-bar ns -> sidebar
* [ ] Rename #status -> .content
* [x] Investigate deprecation message on accessing deprecated variables
* [x] Investigate deprecation message on accessing deprecated namespaces (seems unlikely).
* [ ] Alert skin plugin writers to impending doom
* [ ] Alert bar-contained plugin writers to impending doom

**Comment by cldwalker** [comment]
Closing as interest in this has stalled. Happy to reopen if someone wants to pick it up
